### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tire95** [gitjms/Lyriikka-analysaattori#1]
Projekti ladattu 1.6. klo. 19:16

Yleisiä kommenteja: Koodi on selkeää ja hyvin kirjoitettua. Tietokantataulut ovat järkevät, ja tietokannan toiminnallisuus näyttää toimivan kuten pitääkin (esim. kun käyttäjä poistetaan, poistuu samalla myös käyttäjän lisäämät kappaleet). Lisäksi sovelluksen käyttöliittymä on intuitiivinen. Erittäin perinpohjainen ja hyvä dokumentaatio oli iloinen yllätys, sillä en odottanut, että tässä vaiheessa kukaan olisi keskittynyt siihen.

Koodiin liittyviä kommenteja:

- Muutamassa html-tiedostossa syntaksi on hieman väärin; esim. loginform.html:ssä 

	`<button class="btn btn-sm btn-secondary myFloat_Left" type="submit" name="Back" id="Back" style="width:75px;" value="Back"/>Cancel</button>`

on yksi / liikaa lopussa, juuri kohdan "Back" jälkeen. Oikea muoto olisi 

	<button class="btn btn-sm btn-secondary myFloat_Left" type="submit" name="Back" id="Back" style="width:75px;" value="Back">Cancel</button>

- `auth/views.py` rivillä 60 koodi voisi olla yksinkertaisesti

	`if not hash_bcrypt.checkpw(password,true_password):`

- `songs/views.py` metodissa `songs_edit()` haetaan sama kappale useaan kertaan tietokannasta (aluksi rivillä 127, sitten rivillä 136, ja vielä kerran rivillä 147). Riittää, että kappale haetaan vain rivillä 127, ja muilla kerroilla käytetään jo valmiksi haettua kappaletta

- `admin/views.py` funktio `clear()` kannattaa minusta nimetä eri tavalla tai jakaa kahteen eri metodiin. Tällä hetkellä funktion nimi ei kuvaa hyvin funktion täyttä toiminnallisuutta

- Jos haluat estää käyttäjää lähettämästä tyhjää formia, formien kenttiin voi laittaa validaattoriksi `validators.InputRequired()`

- Monissa html-sivuissa käytit vain yhtä html-formia, ja funktioissa käytit koodipätkää `if request.form.get("Back") == "Back":`. Sama toiminnallisuus saadaan seuraavanlaisella pätkällä html:ssä (otettu omasta projektistani):
```
    <form method="GET" action="{{ url_for('campaigns_register', campaign_id=campaign.id) }}">
        <input type="submit" value="Join campaign"/>
    </form>
```

- Monet elementit html:ssä käyttivät samoja tyylejä, minkä vuoksi olisi hyvä siirtää nämä tyyliseikat CSS-tiedostoon 

Sovelluksen toiminnallisuuteen liittyviä kommenteja:

- Sovellus ei anna muokata kappaleita. Tämä korjaantuu poistamalla rivi `db.session().add(song)` funktiosta `songs_edit()`; pelkkä `db.session().commit()` riittää siirtämään muutokset tietokantaan

- Olisi hyvä, jos kappaleiden muokkaamisessa on mahdollista vaihtaa myös kappaleen kieltä (siltä varalta, että käyttäjä vahingossa valitsi väärän kielen alussa)

- Kun yritin lokaalisti hakea sanaa, sovellus heitti virheviestin 

```
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:
    [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html
```

liittyen tiedoston `words/proc.py` riviin 72 `stops = stopwords.words(language)`. Ilmeisesti nltk ei toimi, vaikka se on asennettu. En siis voinut testata tämän toiminnallisuutta omalla koneellani.

- Kun admin poistaa tai lisää peruskappaleet, sovellus siirtyy näkymään, jossa käyttäjät selvästi on tarkoitus listata, mutta lista on tyhjä. Tiedoston `admin/views.py` funktiossa `clear()` puuttuu kummassakin haarassa lopussa käyttäjien listaus.

- Kun yritin poistaa käyttäjän, sovellus heitti virheviestin `NameError: name 'sumSessionCounter' is not defined` liittyen tiedoston `admin/views.py` riviin 53. Kun testasin Herokussa, tuli `Internal Server Error`

- Herokussa joidenkin sanojen etsiminen epäonnistui, vaikka sana löytyi ainakin yhdessä kappaleessa

**Comment by gitjms** [comment]
Kiitos hyvästä palautteesta. Olen yrittänyt korjata ongelmat, jotka huomasit.
