### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Nurou** [gitjms/Lyriikka-analysaattori#2]
**Time of review:** 2.6.2020 - 21.22.53 Eastern European Summer Time

# What I did

- Read the documentation
- Inspected and used the live application running on Heroku
- Downloaded the project and attempted to run it according to the installation guide
- Scoured through the project's files, inspecting the code in the process
- Ran performance & accessibility audit

# General Comments

- I like the idea of the project. Seems like a prototype for a useful app!
- The project seems to be progressing well. You've got a decent amount of functionality built already.
- Documentation is well done, but the application is somewhat difficult to use.

# Functionality

The following is in the context of what has been stated in the user guide and project description:

- I followed the installation guide but unfortunately could not get the application to run locally - at least one of the issues had to do with the nltk package. I googled for solutions but was not able to get it working on my macOS.
- I was not able to log in as admin, and thus unable to take a look at the functionality offered on the admin side.
- The project topic is explained well in the documentation. However, it might be useful to include something about why a user would use it? It provides functionality for users to inspect word frequencies in certain songs - why is this useful? This may be obvious to you, but I think some description of this would be a plus.
- The application is running on Heroku and can be used to some degree. Good! It does breakdown, however, when navigating to certain pages or manipulating the songs. The project is not meant to be finished, but issues such as the inability to navigate to the home page (under some circumstances) could be/have been fixed relatively painlessly or been warned about in the documentation.
- On second inspection, it does allow me to add songs! There seems to be some inconsistent behaviour. I got server errors at times, and other times it worked. Perhaps it's to do with protecting certain paths.

# Documentation

- Database diagram: what does the BASE entity represent? There is no description of this in the documentation, so that's something you could add if the entity is still relevant.
- The AUTHOR entity is also unclear. Perhaps consider adding some description as to why you've decided to model your database in this particular way. The diagram is unclear to me with regard to BASE and AUTHOR
- The code seems to be self-documenting for the most part. However, there are some instances where it could be improved, especially the 'why' aspect. Yes, it's Python and relatively easy to read, but it's good to provide additional context, esp. as it will be reviewed by your peers. For example, there is a script at the button of your layout template - why is it needed? The same applies to some of the view logic.

# Code Quality

- You've organised your project neatly into packages (e.g. auth and song), with clearly separated concerns.
- All environment variables and sensitive information seem to be out of sight.
- There doesn't seem to be much commented-out/unused code
- A good idea would be to have role as a separate database table, instead of property on the User entity.
- Although the naming throughout the project is generally decent, some of the variable namings could be clearer. For example 'CreateForm' - a more descriptive name would be something like CreateUserForm or RegistrationForm

# Usability & Accessibility

- The HTML is generally semantically written, with proper elements used in a lot of places such as button, nav, etc.
- The code is also accessible in most part. Good use of names, attributes, alt tags, etc.
- You should consider adding headings to the pages that are missing it as well - this provides the document with more structure.
- For accessibility, take a look at the contrast ratio between the background and foreground colors.
- Also, some form elements are missing labels - namely username and password. You should add these in.
- I'm not sure why you've used HTML tables so liberally. For example, the menu search functionality doesn't need a table - a simple div with three nested buttons would have done the job. There are a lot of tables!
- I do think that your layout template is pretty complex - it might be a good idea to do some cleanup and separation there.
- As for the general usability, it's good that you've applied some bootstrap styling to it. The seems to be a lot of clumping together off stuff, e.g. the nav items and the login form parts. Consider aligning the elements in your containers more clearly. For example, the nav items can be spread horizontally. The alignment could be improved in many places, inc. the forms and songs.

**Comment by gitjms** [comment]
Very good comments, thanks. I have tried to fix these issues.
