### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by nnecklace** [gitjms/Lyriikka-analysaattori#3]
Ladattu 15.6.2020 20:49

## Asennus

Asennus onnistui suhteellisen kivuttomasti. Muutamia huomautuksia:

Ohjeissa lukee: 
> [Python](https://www.python.org/downloads/), vähintään 3.8 (bcryptin kanssa ongelmia 3.7-versioissa)

Mutta seuraavassa kappaleessa lukee:

>Mikäli käytät eri Python-versiota kuin 3.7.7, avaa työkansiossa tiedosto *runtime.txt* jollain tekstieditorilla ja muuta siellä oleva ainoa rivi ```python-3.7.7``` vastaamaan omaa Python-versiotasi.

Eli, jäi epäselväksi mikä versio pitää olla asennettuna. Itselläni on 3.7.5 ja kaikki vaikutti toimivan ihan hyvin.

>source venv/Scripts/activate

Tämä on windows spesifinen komento. Kannattaa varmuuden vuoksi lisätä ohjeisiin kommentin, jossa mainitset, että unix (mac, linux) -käyttäjät tulisi ajaa seuraavaa komentoa:
`source venv/bin/activate` (activate on bin-kansion alla unix-käyttöjärjestelmissä)

## Ensivaikutelmat ja user story

Sovellus näyttää hyvältä. Käyttöliittymässä käytetään osittain bootstrappiä sekä custom-css tyylejä. Sain suurin osa _user storeista_ tehtyä. 

>tehdä frekvenssianalyysinä top 10 sanat

En saanut tehtyä. En oikein tiedä mitä tuo tarkoittaa. Eikä käyttöohjeissakaan ollut tarkempaa selitystä. 

>tehdä frekvenssianalyysin tietyn sanan esiintymistiheydestä. 

Tämä onnistuu, paitsi jos jätät kielen valitsematta. Jos näin teet niin ohjelma kaatuu.

```
UnboundLocalError: local variable 'language' referenced before assignment
qry_list = db.session().query(Song.id,Song.lyrics,Song.name,Song.language).filter(Song.account_id.in_(user_list)).filter(Song.language==language).all()
```

Eli `application/words/views.py` tiedostossa rivillä 78-81 yrität estiä lauluja/runoja kielen perusteella. 

```python
	if material == 'Song':
		qry_list = db.session().query(Song.id,Song.lyrics,Song.name,Song.language).filter(Song.account_id.in_(user_list)).filter(Song.language==language).all()
	elif material == 'Poem':
		qry_list = db.session().query(Poem.id,Poem.lyrics,Poem.name,Poem.language).filter(Poem.account_id.in_(user_list)).filter(Poem.language==language).all()
```
Mahdollinen korjaus voisi olla, että lisäät _required_ atribuutin kaikille _language_ -checkbokseille. Tai (ja mielestäni parempi) lisäät tarkistuksen koodiin. 

Vaikka näin:

```python
	if material == 'Song':
		qry = db.session().query(Song.id,Song.lyrics,Song.name,Song.language).filter(Song.account_id.in_(user_list))
	elif material == 'Poem':
		qry = db.session().query(Poem.id,Poem.lyrics,Poem.name,Poem.language).filter(Poem.account_id.in_(user_list))

        if language:
                qry_list = qry.filter_by(language=language).all()
        else:
                qry_list = qry.all()
....
```

Muut storyt sain tehtyä ongelmitta.

## Koodin laatu

Huomasin koodikatselmoidessa muutaman koodiin laatuun liittyvän asian, jotka voisi mahdollisesti aiheuttaa bugeja tai päänvaivaa jatkossa.

1. Jatkuvia rooli tarkistuksia. Koodissa näkyi jatkuvasti sama tarkistus
```python
	if g.user.role != "ADMIN":
		return login_manager.unauthorized()

	if g.user.role != "USER" and g.user.role != "ADMIN":
		return login_manager.unauthorized()
```

Näille tarkistuksille voisi kirjoittaa oman _decorator_ -funktion. Osassa 5 kurssimateriaalissa on hyvä esimerkki miten tätä tehdään. Mutta. tässä tilanteessa voisi tehdä vaikka tämmöisen funktion:

```python
def login_required(_func=None, *, roles=[]):
    def wrapper(func):
        @wraps(func)
        def decorated_view(*args, **kwargs):
            if not (current_user and current_user.is_authenticated):
                return login_manager.unauthorized()

            if current_user.role not in roles:
                return login_manager.unauthorized()

            return func(*args, **kwargs)
        return decorated_view
    return wrapper if _func is None else wrapper(_func)
```

Tämä on siinä mielessä helpompaa, koska nyt sinun ei tarvitse kirjoittaa samaa tarkistusta jatkuvasti vaan voit kirjoittaa esim näin:

```python
@app.route("/poems/edit/<poem_id>/<poet_id>/<from_page>", methods=["GET", "POST"])
@login_required(roles=["ADMIN", "USER"])
def poems_edit(poem_id,poet_id,from_page):
```

2. Muutamassa kohdassa teet toistuvia tietokantakyselyitä

Yksi esimerkki tästä on mm. `application/poems/views.py` riveillä 209-219. 

```python
	if Poet.query.filter_by(name=new_poet.strip()) is None:
		poet = Poet(name=new_poet.strip())
		try:
			db.session().add(poet)
			db.session().commit()
		except SQLAlchemyError:
			db.session.rollback() # <- ei välttämättä tarvita
			flash("Poet not added to database.", "danger")
			return render_template("poems/new.html", form = form)

	poem.poet.extend(Poet.query.filter_by(name=new_poet.strip()))  # <- Haetaan sama poet uudestaan?
```

Tässä voisit laittaa esimmäisen kyselyn vastauksen muuttujaan ja sitten tehdä _None_ tarkistus.

 Samoin tuossa kyseisessä tiedostossa kutsut `db.session.rollback()`, tätä kutsua ei välttämättä tarvita, jos jotain menee pieleen niin sqlalchemy tekee (_pitäisi ainakin_) tämän automaattisesti jos jotain menee pieleen siis.

Toistokyselyt näkyi koodissa aina silloin tällöin, kannattaa varmistaa ettet tee turhia tietokantakyselyitä. 

3. Turhan pitkiä ja jatkuvia if-else tarkistuksia

Koodissa näkyi aika paljon saman kaltaisia if-else tarkistuksia, esim.

```python
		if request.form.get('filter') is not None:
			data = request.form.get('filter').split(',')
			if data[0] == "True":
				filtered = False
			elif data[0] == "False":
				filtered = True
		
		if request.form.get('save') is not None:
			data = request.form.get('save').split(',')
			if data[0] == "True":
				filtered = True
			elif data[0] == "False":
				filtered = False
```

Tästä voisi helposti tehdä yhden funktion joka tekee tuon tarkistuksen kerran ja palauttaa totuusarvon:

```python
def check_data(payload):
	if payload is not None:
		data = payload.split(',')
		if data[0] == "True":
			return False
		elif data[0] == "False":
			return True
	return False
```

Em. laatuasiat eivät sinänsä ole isoja ongelmia. Alalla kutsutaan yleensä tekniseksi velaksi. Esim. jos muuttaisit _ADMIN_ roolin (vaikka _ADMINISTRATOR_:iksi) tietokannassa niin siinä tapauksessa sinun tulisi vaihtaa sitä useammassa paikassa (koodissa). Kun taas jos olisi yksi `admin_required` _decorator_ -funktio joka hoitaisi tämän tarkistuksen niin sinun pitäisi vain muuttaa roolin nimi koodissa kerran. 
 
## Bugeja

Löysin katselmoinnin aikana muutaman bugin. 

1. Loginlomake ei anna virheilmoitusta. Koodin mukaan loginlomake sivulla pitäisi tulla virheilmoitus, jossa kerrotaan mm. 
`flash("No such username or password.", "warning")`

Koodi on oikein kirjoitettu, joten en osaa sanoa miksi näin käy. Tämä tapahtuu ainoastaan login-sivulla.

2. Runojen lisääminen epäonnistuu aina

Jos yrität luoda runon niin lomake kertoo aina, että runoilijan nimi täytyy sisätlää ainakin yhden merkin. Tämä johtuu siitä,  että `application/poems/forms.py` -tiedostossa on _poet_ kenttä, mutta html-lomakkeessa on 
```
<textarea class="form-control text-left" id="poem" name="poem" type="text" rows="1" style="overflow:auto;" placeholder="Firstname Lastname">{{ form.poet().split(">",1)[1] }}</textarea>
```
Eli, _poem_ niminen kenttä. Textarean _name_ -atribuutin arvo pitäisi varmaan olla _poet_.
Korjauksen jälkeen, jos yrität luoda uuden runon, niin ohjelma kaatuu.

```python
AttributeError: 'Poem' object has no attribute 'poet'
poem.poet.extend(Poet.query.filter_by(name=new_poet.strip())
```

Eli, tässä taitaa olla isompi bugi.

3. Salasana salaus

Sovelluksessa käytät bcrypt-kirjastoa mutta taidat käyttää sitä vähän väärällä tavalla. Yleensä kun salasanoja salataan, niin salattu versio säilytetään tietokannassa. Nyt säilytät _plain text_ version salasanasta tietokannassa. Tämä on tosi vaarallinen tapa säilyttää salasanoja! 
https://owasp.org/www-community/vulnerabilities/Password_Plaintext_Storage

https://www.howtogeek.com/434930/why-are-companies-still-storing-passwords-in-plain-text/

https://stackoverflow.com/questions/1197417/why-are-plain-text-passwords-bad-and-how-do-i-convince-my-boss-that-his-treasur

```python
	pw_hash = bcrypt.generate_password_hash(form.password.data)
	user = User(form.name.data,form.username.data,form.password.data)
```

Eli, tuossa pitäisi tehdä näin:

```python
	pw_hash = bcrypt.generate_password_hash(form.password.data)
	user = User(form.name.data,form.username.data,pw_hash)
```

Voit sitten verrata käyttäjän antama salasana tietokannassa olevaan salasanaan.

```python
       bcrypt.check_password_hash(user.password form.password.data)
```

4. `/progress_songs` ja `/progress_poems` eivät vaadi autentikaatiota vaikka varmaan pitäisi.

Eli, käyttäjä voi suoraan kutsua noita rajapintoja ilman sisäänkirjautumista. Koodin mukaan ainoastaan _admin_ käyttäjillä on oikeus kutsua noita rajapintoja. Tätä voit korjata helposti lisäämällä `@login_required` ja admin tarkistuksen.

5. Roles tietokantataulu taitaa olla turha

Tällä hetkellä _roles_ tietokantataulu ei tee mitään. _account_ taulussa on yksi viiteavain _roles_ tauluun, mutta sitä ei oikein hyödynnetä. Tällä hetkellä voin kirjoittaa minkä tahansa arvon _account role_ kenttää. Kentän pitäisi varmaan olla _account role_id_ ja kentän tulisi varmaan viitata _roles_ -taulun id kenttään. 

Eli, tällä hetkellä voin kirjoittaa vaikka: 

`INSERT INTO account (name, username, password, role, date_created) VALUES ('admin', 'admin5', 'admin', 'hölmö_rooli', CURRENT_TIMESTAMP);`

Tarkoitus olisi varmaan kirjoittaa jatkossa näin:
`INSERT INTO account (name, username, password, role_id, date_created) VALUES ('admin', 'admin5', 'admin', 1, CURRENT_TIMESTAMP);`

Missä _role_id_ on _roles_-taulun id kenttä ja id 1 on _admin_-rooli.

6. Yhteenvetokyselyt

Sovelluksessa on useita yhteenvetokyselyitä. mm. 

```sql
SELECT DISTINCT Song.language,
       COUNT(DISTINCT Song.name),
       COUNT(DISTINCT Author.name)
FROM Song
LEFT JOIN author_song ON Song.id = author_song.song_id
LEFT JOIN Author ON author_song.author_id = Author.id
LEFT JOIN account ON account.id = Song.account_id
WHERE account.id IN (1,2)
GROUP BY Song.language
ORDER BY Song.language ASC;
```

Tämä on muuten hyvä, paitsi, että kyselyissä oletetaan, että pääkäyttäjien id:t ovat 1 ja 2. Voi käydä myös niin, että pääkäyttäjien id:t eivät välttämättä ole 1 ja 2. Katselmoinnin aikana minulla kävi juuri näin. Tästä johtuen en pystynyt lataamaan oletusrunoja enkä oletuslauluja, koska pääkäyttäjän id oli 3 tässä tilanteessa. 

```sql
WHERE account.id IN (1,2)
```

Voisi muuttaa vaikka näin.

```sql
WHERE account.id IN (SELECT account.id FROM account WHERE account.role = 'ADMIN' OR account.role = 'GUEST')
```

## Toiveita 

Katselmoinnin aikana tuli muutama toive mieleen. Nämä ovat ainoastaan minun henkilökohtaisia toiveita tällä projektille :) En usko, että nämä toiveet vaikuttaa loppuarvosteluun ollenkaan :D 

1. Jossain tilanteissa tietokantataulujen nnimet oli vähän hämääviä. Joskus taulut olivat monikossa ja joskus ei. Toivoisin että kaikki taulut seuraisi samaa nimeämispolitiikka 🙏 

2. Pliis lisää repoon .gitignore-tiedoston! Gitignore-tiedosto auttaa mm. quick-search:ssä (vs-code ja vim). Nyt kun projektissa ei ole gitignore-tiedostoa niin quick-search kaatuu tai kestää tosi kauan koska se käy läpi kaikki venv-kansion alla olevat tiedostot. Gitignore-tiedosto auttaa myös jos joku muu haluaa tehdä pull-requestin projektille. Jos haluaisin vaikka korjata jotain bugeja sovelluksessa, niin _minun pitäisi nyt_ varmistaa että en vahingossa lisää esim venv-kansion versiohallintaan, tämähän on tietenkin tosi rasittavaa. 

## Summa summarum 

Projekti oli mielestäni tosi hyvä ominaisuuksien toteuttaminen (käyttäjän näkökulmasta) oli tosi helppoa, muutamassa oli joitain bugeja. Projekti on ehkä monimutkaisempi kun muut projektit mutta tämä ei ole minun mielestä huono asia. Projektissa on toteutettu tähän mennessä kaikki parhaan arvosanan vaadittavat ominaisuudet, hienoa! Pieniä bugeja siellä sun täällä, mutta onneksi tässä on vielä viikon verran aikaa parantaa projektia ja korjata bugeja. 

Muista että minun antamat kommentit eivät ole henkilökohtaisia, nämä ovat ainoastaan asioita joita minun mielestä pitäisi parantaa. Ylläpitäjänä saat tietenkin ignorata kaikki minun antamat kommentit :D

**Comment by gitjms** [comment]
Suurkiitos erittäin hyvästä palautteesta. Olen nyt yrittänyt fiksata bugeja ym. kuntoon tämän palautteen perusteella. Taulujen nimipolitiikkaan en nyt kuitenkaan ehdi puuttua.
